void evaluationTests();
void additionTests();
void subtractionTests();
void basicMultiplicationTests();
void distributiveMultiplicationTests();
void fourierMultiplicationTests();
void derivativeTests();
void comparisonTests();
void exponentiationTests();